{% set name = "FunctionalPlus" %}
{% set version = "0.2.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Dobiasd/FunctionalPlus/archive/v{{ version }}-p0.tar.gz
  sha256: 6026e64260afbd6941aaf19559d6e5dc51cbb3e045ef8d8e158d96bcd8651ed6

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make  # [unix]

test:
  commands:
    - test -f ${PREFIX}/include/fplus/fplus.hpp  # [unix]
    - if exist %LIBRARY_PREFIX%\include\fplus\fplus.hpp (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/Dobiasd/FunctionalPlus
  license: BSL-1.0
  license_file: LICENSE
  summary: Functional Programming Library for C++. Write concise and readable C++ code.
  description: FunctionalPlus helps you write concise and readable C++ code.
  doc_url: http://www.editgym.com/fplus-api-search
  dev_url: https://github.com/Dobiasd/FunctionalPlus

extra:
  recipe-maintainers:
    - Dobiasd
