{% set name = "FunctionalPlus" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Dobiasd/FunctionalPlus/archive/v{{ version }}-p0.tar.gz
  sha256: 4a10a981e30b5b63e5b1334c41cfb3aa9aeb02b25dd154f546bed2c39dc463c1

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make  # [unix]

test:
  commands:
    - test -f ${PREFIX}/include/fplus/fplus.hpp  # [unix]
    - if exist %LIBRARY_PREFIX%\include\fplus\fplus.hpp (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/Dobiasd/FunctionalPlus
  license: BSL-1.0
  license_file: LICENSE
  summary: Functional Programming Library for C++. Write concise and readable C++ code.
  description: FunctionalPlus helps you write concise and readable C++ code.
  doc_url: http://www.editgym.com/fplus-api-search
  dev_url: https://github.com/Dobiasd/FunctionalPlus

extra:
  recipe-maintainers:
    - Dobiasd
